from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from sqlalchemy import text
from database import get_read_db
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io, json

router = APIRouter()

@router.get("/{draft_id}/download")
def download_draft(
    draft_id: str,
    db: Session = Depends(get_read_db)
):
    result = db.execute(text("""
        SELECT title, content, word_count, updated_at
        FROM drafts WHERE id = :id
    """), {"id": draft_id}).fetchone()

    if not result:
        raise HTTPException(status_code=404, detail="Draft not found")

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin = Inches(1.2)
        section.bottom_margin = Inches(1.2)
        section.left_margin = Inches(1.3)
        section.right_margin = Inches(1.3)

    # Title
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title_para.add_run(result.title or "Untitled Draft")
    title_run.font.size = Pt(22)
    title_run.font.bold = True
    title_run.font.color.rgb = RGBColor(0x0A, 0x16, 0x28)

    # Metadata line
    meta_para = doc.add_paragraph()
    meta_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta_run = meta_para.add_run(
        f"Words: {result.word_count or 0}  ·  Last saved: {result.updated_at}"
    )
    meta_run.font.size = Pt(9)
    meta_run.font.color.rgb = RGBColor(0x5A, 0x64, 0x80)

    doc.add_paragraph()

    # Horizontal line via border
    border_para = doc.add_paragraph()
    border_para.paragraph_format.space_after = Pt(12)

    # Content
    content = result.content
    text_content = ""

    if isinstance(content, dict):
        text_content = content.get("text", "")
    elif isinstance(content, str):
        try:
            parsed = json.loads(content)
            text_content = parsed.get("text", content)
        except Exception:
            text_content = content

    if text_content:
        paragraphs = text_content.split('\n')
        for para_text in paragraphs:
            if para_text.strip():
                p = doc.add_paragraph()
                run = p.add_run(para_text.strip())
                run.font.size = Pt(12)
                p.paragraph_format.space_after = Pt(8)
                p.paragraph_format.line_spacing = Pt(18)
    else:
        p = doc.add_paragraph()
        run = p.add_run("No content yet.")
        run.font.size = Pt(12)
        run.font.color.rgb = RGBColor(0x5A, 0x64, 0x80)

    # Footer note
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run("Generated by PaperLens · paperlens.research")
    footer_run.font.size = Pt(8)
    footer_run.font.color.rgb = RGBColor(0x9A, 0xA3, 0xB8)
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)

    filename = f"{(result.title or 'draft').replace(' ', '_')[:40]}.docx"
    return StreamingResponse(
        buffer,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )